/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification for Shop Billing System
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * Returns server health status
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary List all products
 */
export declare const ListProductsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    barcode: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    name: zod.ZodString;
    purchasePrice: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    sellingPrice: zod.ZodNumber;
    mrp: zod.ZodNumber;
    unitType: zod.ZodEnum<["PCS", "Kg", "Gram"]>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    sellingPrice: number;
    mrp: number;
    unitType: "PCS" | "Kg" | "Gram";
    createdAt: string;
    barcode?: string | null | undefined;
    purchasePrice?: number | null | undefined;
}, {
    id: number;
    name: string;
    sellingPrice: number;
    mrp: number;
    unitType: "PCS" | "Kg" | "Gram";
    createdAt: string;
    barcode?: string | null | undefined;
    purchasePrice?: number | null | undefined;
}>;
export declare const ListProductsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    barcode: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    name: zod.ZodString;
    purchasePrice: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    sellingPrice: zod.ZodNumber;
    mrp: zod.ZodNumber;
    unitType: zod.ZodEnum<["PCS", "Kg", "Gram"]>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    sellingPrice: number;
    mrp: number;
    unitType: "PCS" | "Kg" | "Gram";
    createdAt: string;
    barcode?: string | null | undefined;
    purchasePrice?: number | null | undefined;
}, {
    id: number;
    name: string;
    sellingPrice: number;
    mrp: number;
    unitType: "PCS" | "Kg" | "Gram";
    createdAt: string;
    barcode?: string | null | undefined;
    purchasePrice?: number | null | undefined;
}>, "many">;
/**
 * @summary Create or update a product
 */
export declare const CreateProductBody: zod.ZodObject<{
    barcode: zod.ZodOptional<zod.ZodString>;
    name: zod.ZodString;
    purchasePrice: zod.ZodOptional<zod.ZodNumber>;
    sellingPrice: zod.ZodNumber;
    mrp: zod.ZodNumber;
    unitType: zod.ZodEnum<["PCS", "Kg", "Gram"]>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    sellingPrice: number;
    mrp: number;
    unitType: "PCS" | "Kg" | "Gram";
    barcode?: string | undefined;
    purchasePrice?: number | undefined;
}, {
    name: string;
    sellingPrice: number;
    mrp: number;
    unitType: "PCS" | "Kg" | "Gram";
    barcode?: string | undefined;
    purchasePrice?: number | undefined;
}>;
/**
 * @summary Look up product by barcode
 */
export declare const GetProductByBarcodeParams: zod.ZodObject<{
    barcode: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    barcode: string;
}, {
    barcode: string;
}>;
export declare const GetProductByBarcodeResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    barcode: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    name: zod.ZodString;
    purchasePrice: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    sellingPrice: zod.ZodNumber;
    mrp: zod.ZodNumber;
    unitType: zod.ZodEnum<["PCS", "Kg", "Gram"]>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    sellingPrice: number;
    mrp: number;
    unitType: "PCS" | "Kg" | "Gram";
    createdAt: string;
    barcode?: string | null | undefined;
    purchasePrice?: number | null | undefined;
}, {
    id: number;
    name: string;
    sellingPrice: number;
    mrp: number;
    unitType: "PCS" | "Kg" | "Gram";
    createdAt: string;
    barcode?: string | null | undefined;
    purchasePrice?: number | null | undefined;
}>;
/**
 * @summary Update a product
 */
export declare const UpdateProductParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateProductBody: zod.ZodObject<{
    barcode: zod.ZodOptional<zod.ZodString>;
    name: zod.ZodOptional<zod.ZodString>;
    purchasePrice: zod.ZodOptional<zod.ZodNumber>;
    sellingPrice: zod.ZodOptional<zod.ZodNumber>;
    mrp: zod.ZodOptional<zod.ZodNumber>;
    unitType: zod.ZodOptional<zod.ZodEnum<["PCS", "Kg", "Gram"]>>;
}, "strip", zod.ZodTypeAny, {
    barcode?: string | undefined;
    name?: string | undefined;
    purchasePrice?: number | undefined;
    sellingPrice?: number | undefined;
    mrp?: number | undefined;
    unitType?: "PCS" | "Kg" | "Gram" | undefined;
}, {
    barcode?: string | undefined;
    name?: string | undefined;
    purchasePrice?: number | undefined;
    sellingPrice?: number | undefined;
    mrp?: number | undefined;
    unitType?: "PCS" | "Kg" | "Gram" | undefined;
}>;
export declare const UpdateProductResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    barcode: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    name: zod.ZodString;
    purchasePrice: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    sellingPrice: zod.ZodNumber;
    mrp: zod.ZodNumber;
    unitType: zod.ZodEnum<["PCS", "Kg", "Gram"]>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    sellingPrice: number;
    mrp: number;
    unitType: "PCS" | "Kg" | "Gram";
    createdAt: string;
    barcode?: string | null | undefined;
    purchasePrice?: number | null | undefined;
}, {
    id: number;
    name: string;
    sellingPrice: number;
    mrp: number;
    unitType: "PCS" | "Kg" | "Gram";
    createdAt: string;
    barcode?: string | null | undefined;
    purchasePrice?: number | null | undefined;
}>;
/**
 * @summary Delete a product
 */
export declare const DeleteProductParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary List all saved bills
 */
export declare const ListBillsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    billNumber: zod.ZodNumber;
    date: zod.ZodString;
    items: zod.ZodArray<zod.ZodObject<{
        productName: zod.ZodString;
        barcode: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        quantity: zod.ZodNumber;
        unitType: zod.ZodString;
        sellingPrice: zod.ZodNumber;
        total: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        sellingPrice: number;
        unitType: string;
        productName: string;
        quantity: number;
        total: number;
        barcode?: string | null | undefined;
    }, {
        sellingPrice: number;
        unitType: string;
        productName: string;
        quantity: number;
        total: number;
        barcode?: string | null | undefined;
    }>, "many">;
    grandTotal: zod.ZodNumber;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    date: string;
    createdAt: string;
    billNumber: number;
    items: {
        sellingPrice: number;
        unitType: string;
        productName: string;
        quantity: number;
        total: number;
        barcode?: string | null | undefined;
    }[];
    grandTotal: number;
}, {
    id: number;
    date: string;
    createdAt: string;
    billNumber: number;
    items: {
        sellingPrice: number;
        unitType: string;
        productName: string;
        quantity: number;
        total: number;
        barcode?: string | null | undefined;
    }[];
    grandTotal: number;
}>;
export declare const ListBillsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    billNumber: zod.ZodNumber;
    date: zod.ZodString;
    items: zod.ZodArray<zod.ZodObject<{
        productName: zod.ZodString;
        barcode: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        quantity: zod.ZodNumber;
        unitType: zod.ZodString;
        sellingPrice: zod.ZodNumber;
        total: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        sellingPrice: number;
        unitType: string;
        productName: string;
        quantity: number;
        total: number;
        barcode?: string | null | undefined;
    }, {
        sellingPrice: number;
        unitType: string;
        productName: string;
        quantity: number;
        total: number;
        barcode?: string | null | undefined;
    }>, "many">;
    grandTotal: zod.ZodNumber;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    date: string;
    createdAt: string;
    billNumber: number;
    items: {
        sellingPrice: number;
        unitType: string;
        productName: string;
        quantity: number;
        total: number;
        barcode?: string | null | undefined;
    }[];
    grandTotal: number;
}, {
    id: number;
    date: string;
    createdAt: string;
    billNumber: number;
    items: {
        sellingPrice: number;
        unitType: string;
        productName: string;
        quantity: number;
        total: number;
        barcode?: string | null | undefined;
    }[];
    grandTotal: number;
}>, "many">;
/**
 * @summary Save a new bill
 */
export declare const CreateBillBody: zod.ZodObject<{
    items: zod.ZodArray<zod.ZodObject<{
        productName: zod.ZodString;
        barcode: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        quantity: zod.ZodNumber;
        unitType: zod.ZodString;
        sellingPrice: zod.ZodNumber;
        total: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        sellingPrice: number;
        unitType: string;
        productName: string;
        quantity: number;
        total: number;
        barcode?: string | null | undefined;
    }, {
        sellingPrice: number;
        unitType: string;
        productName: string;
        quantity: number;
        total: number;
        barcode?: string | null | undefined;
    }>, "many">;
    grandTotal: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    items: {
        sellingPrice: number;
        unitType: string;
        productName: string;
        quantity: number;
        total: number;
        barcode?: string | null | undefined;
    }[];
    grandTotal: number;
}, {
    items: {
        sellingPrice: number;
        unitType: string;
        productName: string;
        quantity: number;
        total: number;
        barcode?: string | null | undefined;
    }[];
    grandTotal: number;
}>;
/**
 * @summary Get billing statistics (total bills, revenue today, total revenue)
 */
export declare const GetBillStatsResponse: zod.ZodObject<{
    totalBills: zod.ZodNumber;
    totalRevenue: zod.ZodNumber;
    todayRevenue: zod.ZodNumber;
    todayBills: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    totalBills: number;
    totalRevenue: number;
    todayRevenue: number;
    todayBills: number;
}, {
    totalBills: number;
    totalRevenue: number;
    todayRevenue: number;
    todayBills: number;
}>;
/**
 * @summary Get a single bill
 */
export declare const GetBillParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetBillResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    billNumber: zod.ZodNumber;
    date: zod.ZodString;
    items: zod.ZodArray<zod.ZodObject<{
        productName: zod.ZodString;
        barcode: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        quantity: zod.ZodNumber;
        unitType: zod.ZodString;
        sellingPrice: zod.ZodNumber;
        total: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        sellingPrice: number;
        unitType: string;
        productName: string;
        quantity: number;
        total: number;
        barcode?: string | null | undefined;
    }, {
        sellingPrice: number;
        unitType: string;
        productName: string;
        quantity: number;
        total: number;
        barcode?: string | null | undefined;
    }>, "many">;
    grandTotal: zod.ZodNumber;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    date: string;
    createdAt: string;
    billNumber: number;
    items: {
        sellingPrice: number;
        unitType: string;
        productName: string;
        quantity: number;
        total: number;
        barcode?: string | null | undefined;
    }[];
    grandTotal: number;
}, {
    id: number;
    date: string;
    createdAt: string;
    billNumber: number;
    items: {
        sellingPrice: number;
        unitType: string;
        productName: string;
        quantity: number;
        total: number;
        barcode?: string | null | undefined;
    }[];
    grandTotal: number;
}>;
/**
 * @summary Delete a bill
 */
export declare const DeleteBillParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
//# sourceMappingURL=api.d.ts.map