/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification for Shop Billing System
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export type ProductUnitType = typeof ProductUnitType[keyof typeof ProductUnitType];


export const ProductUnitType = {
  PCS: 'PCS',
  Kg: 'Kg',
  Gram: 'Gram',
} as const;

export interface Product {
  id: number;
  /** @nullable */
  barcode?: string | null;
  name: string;
  /** @nullable */
  purchasePrice?: number | null;
  sellingPrice: number;
  mrp: number;
  unitType: ProductUnitType;
  createdAt: string;
}

export type ProductInputUnitType = typeof ProductInputUnitType[keyof typeof ProductInputUnitType];


export const ProductInputUnitType = {
  PCS: 'PCS',
  Kg: 'Kg',
  Gram: 'Gram',
} as const;

export interface ProductInput {
  barcode?: string;
  name: string;
  purchasePrice?: number;
  sellingPrice: number;
  mrp: number;
  unitType: ProductInputUnitType;
}

export type ProductUpdateUnitType = typeof ProductUpdateUnitType[keyof typeof ProductUpdateUnitType];


export const ProductUpdateUnitType = {
  PCS: 'PCS',
  Kg: 'Kg',
  Gram: 'Gram',
} as const;

export interface ProductUpdate {
  barcode?: string;
  name?: string;
  purchasePrice?: number;
  sellingPrice?: number;
  mrp?: number;
  unitType?: ProductUpdateUnitType;
}

export interface BillItem {
  productName: string;
  /** @nullable */
  barcode?: string | null;
  quantity: number;
  unitType: string;
  sellingPrice: number;
  total: number;
}

export interface Bill {
  id: number;
  billNumber: number;
  date: string;
  items: BillItem[];
  grandTotal: number;
  createdAt: string;
}

export interface BillInput {
  items: BillItem[];
  grandTotal: number;
}

export interface BillStats {
  totalBills: number;
  totalRevenue: number;
  todayRevenue: number;
  todayBills: number;
}

