/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification for Shop Billing System
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List all products
 */
export const ListProductsResponseItem = zod.object({
  "id": zod.number(),
  "barcode": zod.string().nullish(),
  "name": zod.string(),
  "purchasePrice": zod.number().nullish(),
  "sellingPrice": zod.number(),
  "mrp": zod.number(),
  "unitType": zod.enum(['PCS', 'Kg', 'Gram']),
  "createdAt": zod.string()
})
export const ListProductsResponse = zod.array(ListProductsResponseItem)


/**
 * @summary Create or update a product
 */
export const CreateProductBody = zod.object({
  "barcode": zod.string().optional(),
  "name": zod.string(),
  "purchasePrice": zod.number().optional(),
  "sellingPrice": zod.number(),
  "mrp": zod.number(),
  "unitType": zod.enum(['PCS', 'Kg', 'Gram'])
})


/**
 * @summary Look up product by barcode
 */
export const GetProductByBarcodeParams = zod.object({
  "barcode": zod.coerce.string()
})

export const GetProductByBarcodeResponse = zod.object({
  "id": zod.number(),
  "barcode": zod.string().nullish(),
  "name": zod.string(),
  "purchasePrice": zod.number().nullish(),
  "sellingPrice": zod.number(),
  "mrp": zod.number(),
  "unitType": zod.enum(['PCS', 'Kg', 'Gram']),
  "createdAt": zod.string()
})


/**
 * @summary Update a product
 */
export const UpdateProductParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateProductBody = zod.object({
  "barcode": zod.string().optional(),
  "name": zod.string().optional(),
  "purchasePrice": zod.number().optional(),
  "sellingPrice": zod.number().optional(),
  "mrp": zod.number().optional(),
  "unitType": zod.enum(['PCS', 'Kg', 'Gram']).optional()
})

export const UpdateProductResponse = zod.object({
  "id": zod.number(),
  "barcode": zod.string().nullish(),
  "name": zod.string(),
  "purchasePrice": zod.number().nullish(),
  "sellingPrice": zod.number(),
  "mrp": zod.number(),
  "unitType": zod.enum(['PCS', 'Kg', 'Gram']),
  "createdAt": zod.string()
})


/**
 * @summary Delete a product
 */
export const DeleteProductParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary List all saved bills
 */
export const ListBillsResponseItem = zod.object({
  "id": zod.number(),
  "billNumber": zod.number(),
  "date": zod.string(),
  "items": zod.array(zod.object({
  "productName": zod.string(),
  "barcode": zod.string().nullish(),
  "quantity": zod.number(),
  "unitType": zod.string(),
  "sellingPrice": zod.number(),
  "total": zod.number()
})),
  "grandTotal": zod.number(),
  "createdAt": zod.string()
})
export const ListBillsResponse = zod.array(ListBillsResponseItem)


/**
 * @summary Save a new bill
 */
export const CreateBillBody = zod.object({
  "items": zod.array(zod.object({
  "productName": zod.string(),
  "barcode": zod.string().nullish(),
  "quantity": zod.number(),
  "unitType": zod.string(),
  "sellingPrice": zod.number(),
  "total": zod.number()
})),
  "grandTotal": zod.number()
})


/**
 * @summary Get billing statistics (total bills, revenue today, total revenue)
 */
export const GetBillStatsResponse = zod.object({
  "totalBills": zod.number(),
  "totalRevenue": zod.number(),
  "todayRevenue": zod.number(),
  "todayBills": zod.number()
})


/**
 * @summary Get a single bill
 */
export const GetBillParams = zod.object({
  "id": zod.coerce.number()
})

export const GetBillResponse = zod.object({
  "id": zod.number(),
  "billNumber": zod.number(),
  "date": zod.string(),
  "items": zod.array(zod.object({
  "productName": zod.string(),
  "barcode": zod.string().nullish(),
  "quantity": zod.number(),
  "unitType": zod.string(),
  "sellingPrice": zod.number(),
  "total": zod.number()
})),
  "grandTotal": zod.number(),
  "createdAt": zod.string()
})


/**
 * @summary Delete a bill
 */
export const DeleteBillParams = zod.object({
  "id": zod.coerce.number()
})


