/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification for Shop Billing System
 * OpenAPI spec version: 0.1.0
 */
import type { BillItem } from './billItem';

export interface Bill {
  id: number;
  billNumber: number;
  date: string;
  items: BillItem[];
  grandTotal: number;
  createdAt: string;
}
