/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification for Shop Billing System
 * OpenAPI spec version: 0.1.0
 */
export interface BillItem {
    productName: string;
    /** @nullable */
    barcode?: string | null;
    quantity: number;
    unitType: string;
    sellingPrice: number;
    total: number;
}
//# sourceMappingURL=billItem.d.ts.map