/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification for Shop Billing System
 * OpenAPI spec version: 0.1.0
 */
export * from './bill';
export * from './billInput';
export * from './billItem';
export * from './billStats';
export * from './errorResponse';
export * from './healthStatus';
export * from './product';
export * from './productInput';
export * from './productInputUnitType';
export * from './productUnitType';
export * from './productUpdate';
export * from './productUpdateUnitType';
//# sourceMappingURL=index.d.ts.map