/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification for Shop Billing System
 * OpenAPI spec version: 0.1.0
 */
export type ProductUnitType = typeof ProductUnitType[keyof typeof ProductUnitType];
export declare const ProductUnitType: {
    readonly PCS: "PCS";
    readonly Kg: "Kg";
    readonly Gram: "Gram";
};
//# sourceMappingURL=productUnitType.d.ts.map