/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification for Shop Billing System
 * OpenAPI spec version: 0.1.0
 */
import type { ProductInputUnitType } from './productInputUnitType';
export interface ProductInput {
    barcode?: string;
    name: string;
    purchasePrice?: number;
    sellingPrice: number;
    mrp: number;
    unitType: ProductInputUnitType;
}
//# sourceMappingURL=productInput.d.ts.map