/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification for Shop Billing System
 * OpenAPI spec version: 0.1.0
 */

export type ProductUpdateUnitType = typeof ProductUpdateUnitType[keyof typeof ProductUpdateUnitType];


export const ProductUpdateUnitType = {
  PCS: 'PCS',
  Kg: 'Kg',
  Gram: 'Gram',
} as const;
