/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification for Shop Billing System
 * OpenAPI spec version: 0.1.0
 */
export type ProductInputUnitType = typeof ProductInputUnitType[keyof typeof ProductInputUnitType];
export declare const ProductInputUnitType: {
    readonly PCS: "PCS";
    readonly Kg: "Kg";
    readonly Gram: "Gram";
};
//# sourceMappingURL=productInputUnitType.d.ts.map