/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification for Shop Billing System
 * OpenAPI spec version: 0.1.0
 */
export type ProductUpdateUnitType = typeof ProductUpdateUnitType[keyof typeof ProductUpdateUnitType];
export declare const ProductUpdateUnitType: {
    readonly PCS: "PCS";
    readonly Kg: "Kg";
    readonly Gram: "Gram";
};
//# sourceMappingURL=productUpdateUnitType.d.ts.map