/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification for Shop Billing System
 * OpenAPI spec version: 0.1.0
 */
import type { ProductUpdateUnitType } from './productUpdateUnitType';

export interface ProductUpdate {
  barcode?: string;
  name?: string;
  purchasePrice?: number;
  sellingPrice?: number;
  mrp?: number;
  unitType?: ProductUpdateUnitType;
}
