/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification for Shop Billing System
 * OpenAPI spec version: 0.1.0
 */
import type { ProductUnitType } from './productUnitType';
export interface Product {
    id: number;
    /** @nullable */
    barcode?: string | null;
    name: string;
    /** @nullable */
    purchasePrice?: number | null;
    sellingPrice: number;
    mrp: number;
    unitType: ProductUnitType;
    createdAt: string;
}
//# sourceMappingURL=product.d.ts.map